<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6cad93cd-277a-417b-8d20-e4f2079bd9a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prod-cart']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cart-prod > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ba20b57-40b4-464d-8d5f-37c03e1fca06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>media/darthvader.jpg</value>
      <webElementGuid>64d80813-2b72-49ae-a1a7-b106dfa7df66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prod-cart&quot;)/div[@class=&quot;cart-prod&quot;]/img[1]</value>
      <webElementGuid>145f2df2-8063-4fe9-8da9-403bf627d452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prod-cart']/div/img</value>
      <webElementGuid>556379dd-c62a-4713-bbcf-bc356ec3749b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>8e09b9e3-b15a-4fae-b00d-99fbc5513827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'media/darthvader.jpg']</value>
      <webElementGuid>a4e8630d-27f4-4b01-ac2e-cf90c801bd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
