<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_icon</name>
   <tag></tag>
   <elementGuidId>3ab56de9-562f-46e8-8200-8c3846c2fcb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-cart-shopping</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@value='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4ed3d38c-0eed-4720-88a2-7b3a687e7e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-cart-shopping</value>
      <webElementGuid>d1b0cd6b-7d1a-4b5f-aff7-b98ab2d58186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46706213-6258-4e9e-b1a4-f406282e7482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a62a60a7-599c-4100-8be6-538a07d3513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Shopping cart with 0 items</value>
      <webElementGuid>521d1f63-e154-4ac1-8bb8-54efb79b17e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;nav-container&quot;]/div[@class=&quot;nav-web&quot;]/span[@class=&quot;user-wrapper&quot;]/a[2]/i[@class=&quot;fa-solid fa-cart-shopping&quot;]</value>
      <webElementGuid>d2612a7a-13fb-4a7c-b4c4-cb24040eb606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@value='0']</value>
      <webElementGuid>00f32c37-cf4e-46fe-851b-49462d76e3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>b926f771-d6d7-49b0-b128-fffd1ace2038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
