<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_icon</name>
   <tag></tag>
   <elementGuidId>c015790a-a5e2-476b-b1ea-1124c51ba50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>79cec70b-d419-47f5-912b-2a60b0bed1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-user</value>
      <webElementGuid>04a8382a-0185-4a63-82b1-eaf3f8daa9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ffd7694-4f71-4f9f-8ffc-dca26467351d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;nav-container&quot;]/div[@class=&quot;nav-web&quot;]/span[@class=&quot;user-wrapper&quot;]/a[1]/i[@class=&quot;fa-solid fa-user&quot;]</value>
      <webElementGuid>fde38b21-81c2-4dae-b72d-0db0e4463cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>149885fe-c736-4621-b105-6ad132a02e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
