<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>youtube_iframe</name>
   <tag></tag>
   <elementGuidId>5e5ec6eb-3771-4e11-82fb-e6bf3dd40499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframe1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>427f7616-e66e-4805-bc25-c82d1995afc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe1</value>
      <webElementGuid>2b826bad-8ccc-4a30-b718-0e098477dca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>560</value>
      <webElementGuid>6e5884b9-861b-4ff4-b6dd-d8aa585cedbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>315</value>
      <webElementGuid>19a3886a-befb-4aa0-a493-33fed9d099e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/Vx0Z6LplaMU?si=sk1uTwBPAIP8t1KS</value>
      <webElementGuid>2d823809-71da-4bd7-9f05-97e1e316cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>YouTube video player</value>
      <webElementGuid>2d6ee61f-1ac0-4c22-b248-eb40cbaa6633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef785464-d61f-48b1-95c0-6b18f8f20c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>79317701-7374-4d42-b530-4686670e81db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe1&quot;)</value>
      <webElementGuid>e5d2e3b8-aacd-4c36-b3d1-ff169897054c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe1']</value>
      <webElementGuid>c8eee957-6a18-47cb-9fa9-779f2b56ed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>45e1005e-382c-48db-b0d6-7e4eed30c683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe1' and @src = 'https://www.youtube.com/embed/Vx0Z6LplaMU?si=sk1uTwBPAIP8t1KS' and @title = 'YouTube video player']</value>
      <webElementGuid>04efc213-eac6-43ae-ab1b-e6e907605056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
