<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password_new-password</name>
   <tag></tag>
   <elementGuidId>deb93b25-31a6-4393-87a9-02429cd6725c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>507e7eae-2432-4ed6-beda-92930b169ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>52a7a5f7-4cf1-44e1-8f17-21c48bd8eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>f9e3a3de-99d4-4938-8f4c-eaeb5f88d6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new-pass</value>
      <webElementGuid>aeacc701-91bf-470f-aeaf-53b6b6998bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your new password</value>
      <webElementGuid>b0ca224d-7307-420a-a408-fb0dc7773dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-password&quot;)</value>
      <webElementGuid>6ab39cd7-c95c-45b9-9d47-7e919569666c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-password']</value>
      <webElementGuid>b2307413-9111-48f7-a506-2eb19b980816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/input[3]</value>
      <webElementGuid>1f985a78-4292-4d95-8d6a-1c56378bbf0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>dc31f5e4-17d7-4cf2-acab-4c85df15b14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'new-password' and @name = 'new-pass' and @placeholder = 'Your new password']</value>
      <webElementGuid>de1a7ab9-aee4-4621-9a3f-51c3122e201a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
