<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code sent to the associated email_code</name>
   <tag></tag>
   <elementGuidId>fdecab2a-aa86-4575-acda-e43e53984e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a239204b-b60b-4515-863d-2faac5750a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>983963be-ad93-4efa-8bbf-edc61e092a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>0bdc2b2f-2e11-4b9c-bb13-c84f89abbdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>38e667ee-a30f-49f5-a94e-d77e17dcf2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your code</value>
      <webElementGuid>7e72dcb7-8d4d-453c-826e-9eddceb05f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code&quot;)</value>
      <webElementGuid>09d8c1cd-3dd7-4694-9e0c-cc75ad02ee8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='code']</value>
      <webElementGuid>f3b4a7cb-ba08-4e48-8303-80a801b292f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/input[2]</value>
      <webElementGuid>2d3ddb86-8f63-436f-9f69-502db3af75e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>0e030f0b-b32d-4d6f-a786-9deab14580c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'code' and @name = 'code' and @placeholder = 'Your code']</value>
      <webElementGuid>2d5b0a41-390c-467d-9f1e-8c3aced32abe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
