<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_password_input</name>
   <tag></tag>
   <elementGuidId>12288e07-3205-46a6-bfea-760b8b60ae14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15e98b69-6106-4fed-a48a-1d33161c4b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cbbb3f1c-04c8-45dd-8196-5c63059863be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-password</value>
      <webElementGuid>4633ba50-aa10-4cf3-862a-cf16a4c1c7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-password</value>
      <webElementGuid>b20987a9-666e-40ca-93d5-75d1dadcf51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repeat your password</value>
      <webElementGuid>a17dd2fc-7f96-41ac-93be-d1caf6589bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-password&quot;)</value>
      <webElementGuid>6d6a6d59-d23c-4abf-a9a6-27799c97e016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm-password']</value>
      <webElementGuid>a537467d-b4ab-41c2-879c-c78f4b0d1fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register-form']/input[5]</value>
      <webElementGuid>36cd87b0-7b9f-44fd-a1a7-1c55321ea0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>26a22602-03be-49a9-93ad-0056217d257f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'confirm-password' and @name = 'confirm-password' and @placeholder = 'Repeat your password']</value>
      <webElementGuid>355f4564-e7cf-4b8a-95c1-f2f77927c423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
