<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_message</name>
   <tag></tag>
   <elementGuidId>21942b3c-af95-4fe4-9ab0-223a7bd3343b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='register-msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0c17256-d8cf-4541-86a3-4169c2f9de7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-msg</value>
      <webElementGuid>91e88712-eb9e-4285-8df6-1ac5dbf40eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-msg</value>
      <webElementGuid>3f716481-4d9f-4d3e-994d-bdbe9ca2d21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>28afe505-b7e5-4065-b803-e2d7a292714d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-msg&quot;)</value>
      <webElementGuid>77ef4703-3d13-4a44-83b6-fe88680e3c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='register-msg']</value>
      <webElementGuid>10904820-db4d-4269-a879-0fbae7eafb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register-form']/div</value>
      <webElementGuid>6f2ea7bc-5d7b-45ed-bc5d-6550474f3413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>0927101c-6d82-4f6a-8206-2ab21461b456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'register-msg']</value>
      <webElementGuid>1aa37a91-972a-4a69-8380-0b505b1bfb5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
