<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry_expiry</name>
   <tag></tag>
   <elementGuidId>19417a0b-471c-414c-b3d9-ded74031ef68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>239119ee-3bc1-45d0-93bc-db7787964f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>511e1001-6180-45ca-a4c3-0667541e9a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-input</value>
      <webElementGuid>bce9dea0-e6e5-4993-9baf-505a0c6a5530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abfc23ca-8e4f-491c-a6b3-410796a3d862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>11bc831e-4729-4d47-a196-f7d4c4a59dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>35b63d36-a95c-4cfd-905e-3defc20e3a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>9b5ceba9-bc60-4183-a8ee-d9652139a638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkout-form']/div[2]/div[2]/input</value>
      <webElementGuid>e2b6c458-e058-4f4d-a65e-ab21cbaa5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>16f9dbbc-4783-4a8b-9494-614fab9a3321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiry' and @type = 'text' and @placeholder = 'MM/YY']</value>
      <webElementGuid>2624e688-cd99-44e1-b59f-c1bea28feb84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
